export const Roles={PUBLIC:"PUBLIC",RESPONDENT:"RESPONDENT",CLIENT:"CLIENT",AIRS_OPERATOR:"AIRS_OPERATOR"};
export const EngagementStates=["CREATED","MANAGEMENT_COMPLETE","TEAM_COLLECTION_OPEN","TEAM_COLLECTION_COMPLETE","PRIVACY_TRANSFORMED","RECONCILIATION_READY","REVIEW_REQUIRED","REPORT_DRAFT","AIRS_APPROVED","DELIVERED"];
